[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32H753ZITx --probe 0483:374e:001C00253234511133353533"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
